const teams = [
    { id: 'ana', name: 'Los Angeles Angels', logo: './logos/ana_108.png' },
    { id: 'ari', name: 'Arizona Diamondbacks', logo: './logos/ari_109.png' },
    { id: 'atl', name: 'Atlanta Braves', logo: './logos/atl_144.png' },
    { id: 'bal', name: 'Baltimore Orioles', logo: './logos/bal_110.png' },
    { id: 'bos', name: 'Boston Red Sox', logo: './logos/bos_111.png' },
    { id: 'chc', name: 'Chicago Cubs', logo: './logos/chc_112.png' },
    { id: 'chw', name: 'Chicago White Sox', logo: './logos/chw_145.png' },
    { id: 'cin', name: 'Cincinnati Reds', logo: './logos/cin_113.png' },
    { id: 'cle', name: 'Cleveland Guardians', logo: './logos/cle_114.png' },
    { id: 'col', name: 'Colorado Rockies', logo: './logos/col_115.png' },
    { id: 'det', name: 'Detroit Tigers', logo: './logos/det_116.png' },
    { id: 'hou', name: 'Houston Astros', logo: './logos/hou_117.png' },
    { id: 'kcr', name: 'Kansas City Royals', logo: './logos/kcr_118.png' },
    { id: 'lad', name: 'Los Angeles Dodgers', logo: './logos/lad_119.png' },
    { id: 'mia', name: 'Miami Marlins', logo: './logos/mia_146.png' },
    { id: 'mil', name: 'Milwaukee Brewers', logo: './logos/mil_158.png' },
    { id: 'min', name: 'Minnesota Twins', logo: './logos/min_142.png' },
    { id: 'nym', name: 'New York Mets', logo: './logos/nym_121.png' },
    { id: 'nyy', name: 'New York Yankees', logo: './logos/nyy_147.png' },
    { id: 'oak', name: 'Oakland Athletics', logo: './logos/oak_133.png' },
    { id: 'phi', name: 'Philadelphia Phillies', logo: './logos/phi_143.png' },
    { id: 'pit', name: 'Pittsburgh Pirates', logo: './logos/pit_134.png' },
    { id: 'sdp', name: 'San Diego Padres', logo: './logos/sdp_135.png' },
    { id: 'sea', name: 'Seattle Mariners', logo: './logos/sea_136.png' },
    { id: 'sfg', name: 'San Francisco Giants', logo: './logos/sfg_137.png' },
    { id: 'stl', name: 'St. Louis Cardinals', logo: './logos/stl_138.png' },
    { id: 'tbr', name: 'Tampa Bay Rays', logo: './logos/tbr_139.png' },
    { id: 'tex', name: 'Texas Rangers', logo: './logos/tex_140.png' },
    { id: 'tor', name: 'Toronto Blue Jays', logo: './logos/tor_141.png' },
    { id: 'was', name: 'Washington Nationals', logo: './logos/was_120.png' }
];